### ISSUE TITLE
Network issues on kubernetes

### ISSUE THREAD

**Issue by dgoradia** [ruby-shoryuken/shoryuken#600]
When we setup the workers on kubernetes, it seems to be really noisy on the network and starts to cause http health checks for other pods to start to error with 502.

Has anyone else seen this or come to a possible solution?

We're switched to long polling and while that's lessened the amounts of 502s we are getting they're still persistent. We've also moved the workers onto their own node group which again continues to cause these failures in other services. 

The only way to fix it that I've found is to not have the workers in the kubernetes cluster and put them on just n ec2 instance, which is far form ideal in our case.

**Comment by silasb** [comment]
We just started testing on K8s this week....  The biggest tweak that we did was increasing the delay.  With the default of 0 it was causing a lot of network traffic.  Setting it to 1 second was a good balance for our jobs.

Have you tweaked any of the settings?  If so, care to share?

**Comment by tibbon** [comment]
We're using it in k8s without a problem right now, but I'd like to know/hear more about what's happening in case we do run into something.

**Comment by truongnmt** [comment]
>  noisy on the network and starts to cause http health checks for other pods to start to error with 502.

We also running live in k8s without above problems.

**Comment by tibbon** [comment]
Here's my basic deployment.yaml file for kubernetes. Nothing special at all happening, but I haven't noticed noise either.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqs-worker
  labels:
    app: sqsi-worker
spec:
  selector:
    matchLabels:
      app: sqs-worker
  template:
    metadata:
      labels:
        app: sqs-worker
    spec:
      serviceAccountName: sqs-worker
      containers:
      - name: sqs-worker
        imagePullPolicy: IfNotPresent
        image: gitlab-registry.example.net/images/sqs-worker:main-1
        envFrom:
          - configMapRef:
              name: sqs-worker.sqs.config
        command: ["bundle", "exec", "shoryuken", "-r", "./lib/worker.rb", "-C", "./config/shoryuken.yml"]
        resources:
          requests: # These surely need to be altered!
            cpu: 100m 
            memory: 100Mi

```
