### ISSUE TITLE
No worker found for queue in rails application

### ISSUE THREAD

**Issue by raiprabh** [ruby-shoryuken/shoryuken#639]
I am trying to test out my rails application with shoryuken. I have the worker configured as follows:

```
class BackgroundWorker
  include Shoryuken::Worker

  worker_queues = ["queue_local"]

  shoryuken_options queue: worker_queues, auto_delete: true

  def perform(sqs_msg, body)
    puts sqs_msg
  end
```

My shoryuken.yml file looks like this:

```
aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  receive_message:
    attribute_names:
    - ApproximateReceiveCount
    - SentTimestamp
  region: us-west-2
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
concurrency: 1
pool: 1
delay: 0
```

I am running the server by: `bundle exec shoryuken -q queue_local -C ./config/shoryuken.yml -R`

This queue is on my AWS SQS. I have a message in it. The error that shows up is:

```
{"timestamp":"2020-11-29T15:00:30Z","process_id":13448,"thread_id":"TID-gq2w80guk","level":"ERROR","dd":{"trace_id":0,"span_id":0},"ddsource":["ruby"],"format":"json","message":"No worker found for queue_local"}
```

Can you please tell me what is wrong here?

**Comment by dhanashrij-cuelogic** [comment]
Try updating shoryuken.yml as-

```
aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY"] %>
  receive_message:
    attribute_names:
    - ApproximateReceiveCount
    - SentTimestamp
  region: us-west-2
  secret_access_key: <%= ENV["AWS_SECRET_KEY"] %>
concurrency: 1
pool: 1
delay: 0
queues:
  - queue_local
```

and try executing following command from application root directory -

`bundle exec shoryuken -R -C config/shoryuken.yml`
