### ISSUE TITLE
Question: how to optimally configure priority queues with long polling

### ISSUE THREAD

**Issue by bforma** [ruby-shoryuken/shoryuken#695]
Hi,

We have two separate SQS queues, one for 'default priority' messages and one for 'low priority' messages.

I've tried to configure handling these with Shoryuken as follows:

```yaml
polling_strategy: StrictPriority
queues:
  - default_priority
  - low_priority
```

But when we use this with long polling (`Shoryuken.sqs_client_receive_message_opts = {wait_time_seconds: 20}`) the throughput drastically decreases (because each queue is checked one by one with a wait time of 20 seconds in between).

As a workaround we now run most Shoryuken workers with `-q default_priority` and several with `-q low_priority`.

Any thoughts on a more optimal configuration/setup?
