### ISSUE TITLE
Environment Variables in *.yml files are not resolved 

### ISSUE THREAD

**Issue by girishgl** [ruby-shoryuken/shoryuken#728]
I am not able to read environment variables from yml file while starting shoryuken worker

 `bundle exec shoryuken --daemon --pidfile '/tmp/pids/shoryuken.pid' --logfile '/app/log/application.log' --config "/app/config/shoryuken.$RAILS_ENV.yml" --rails
`

shoryuken.production.yml

```

aws:
  region: us-east-1
  ssl_verify_peer: false
concurrency: 64
delay: 5
queues:
  - <%= ENV["XYZ_QUEUE"] %>
  - <%= ENV["ABC_QUEUE"] %>
  
```

These environments variables are set in config/application.rb

```
# load environment variables from .env files
require 'dotenv'
Dotenv.load


Dotenv.load('.env.test') if ENV['RAILS_ENV'] == 'test'

require 'aws-sdk-secretsmanager'
client = Aws::SecretsManager::Client.new(region: ENV['AWS_SECRET_MANAGER_REGION']  )

secrets_path = "xyz/#{ENV['RAILS_ENV']}".downcase
secrets = client.get_secret_value(secret_id: secrets_path).secret_string
JSON.parse(secrets).each_pair { |k, v| ENV["#{k}".upcase] = v }
```
