### ISSUE TITLE
Doubt about threads opened with concurrency in groups

### ISSUE THREAD

**Issue by andreleoni** [ruby-shoryuken/shoryuken#729]
Hello, I have a doubt.

If I have the following scenario;

```
groups:
  group1:
    concurrency: 10
    queues:
      - queue1
  group2:
    concurrency: 10
    delay: 10
    queues:
      - queue2
```

How many threads will be opened in our application? It will be the sum of each group, 20? Or will be the limit of the greatest concurrency parameter?

I'm asking it, because this concurrency shoud be the same as the database pool config, right? Otherwise, we can have problems of postgres without connection to execute the job. In this case, if the concurrency duplicate the value with the sum of groups, whats is recommended?

**Comment by matt-taylor** [comment]
Hi @andreleoni 
Each Shoryuken group executes in a separate thread (2 threads). Each Group will then spin up a maximum of `concurrency` threads to process messages concurrently (10 threads).

With 2 groups of concurrency 10, Shoryuken will create a maximum 20 concurrent promises at any given time.  

---



> I'm asking it, because this concurrency shoud be the same as the database pool config, right? Otherwise, we can have problems of postgres without connection to execute the job.

Yes. If your Shoryuken workers require a database connection, it is critical that your DB connection matches the max concurrency otherwise you will have an ActiveRecord Pool timeout. 
I would advise declaring the concurrency in Shoryuken config the same way you do in your database config file:
```yaml
groups:
  group1:
    concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5).to_i / 2 %>
    queues:
      - queue1
  group2:
    concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5).to_i / 2 %>
    delay: 10
    queues:
      - queue2
```
Where `RAILS_MAX_THREADS` is the variable that defines pool count in your database yaml file


In your case please be mindful that some code may also spin up additional threads that require a DB connection. This may force you to add additional overhead during peaks.

---

> In this case, if the concurrency duplicate the value with the sum of groups, whats is recommended?

This depends on the operating machine and how thread safe your code is. By default, Shoryuken operates with 25 concurrency unless `concurrency` flag is passed in.

**Comment by andreleoni** [comment]
Thank you very much for the clarifications!

---

In this case, I will use an env var to set the max db threads when using shoryuken queues, with the maximum of threads that we can support, and each group with the concurrency that we desire accourding with the queue throughput. 

For example:

File: `config/database.yml`

```
default: &default
  ...
  pool: <%=
    if $0 =~ /shoryuken/
      ENV.fetch('SHORYUKEN_MAX_NUM_OF_THREADS_CONCURRENCY', 15)
    else
      ENV.fetch('DB_POOL', 2)
    end %>
``` 

And on the groups, I use something like:

File: `shoryuken.yaml`

```
groups:
  group1:
    concurrency: <%= ENV.fetch('SHORYUKEN_GROUP1_CONCURRENCY', 10).to_i %>
    queues:
      - queue1
  group2:
    concurrency: <%= ENV.fetch('SHORYUKEN_GROUP2_CONCURRENCY', 4).to_i %>
    delay: 10
    queues:
      - queue2
  fifo:
    concurrency: 1    
    queues:
      - queue-fifo-1
```

In this way, a as the sum of the groups, is the maximum value of connections in the db pool. And we have flexibility to rearrange the pool connections to tune our containers.

With it, I solve our problem!

---

So, for me the issue is solved, so, you recommend me to update the documentation with this "information"?

If yes, I can update this section? https://github.com/ruby-shoryuken/shoryuken/wiki/Processing-Groups
