### ISSUE TITLE
Doubt about delay in groups

### ISSUE THREAD

**Issue by andreleoni** [ruby-shoryuken/shoryuken#730]
Hello,

I was configuring the `delay` of my groups, and I got a doubt.

If I have the follow scenario:

```
groups:
  default:
    concurrency: 10
    delay: 20
    queues:
      - queue1
      - queue2
```

It means that, we will pull the messages for the queue1, and after 20 seconds, will pull messages for queue2? (Something like a delay between get messages from each queue)

Or will be, pull messages of queue1, and after, messages of queue2, and wait 20 seconds to pull the two queues again? (Something like a delay between get messages from all processing group queue)

I was choosing the best approach about the usage of `delay`, or the `long pulling`, and this behaviour is essencial to decide it.
