### ISSUE TITLE
Can concurrency be shared across groups (Managers) ?

### ISSUE THREAD

**Issue by gurukannappa** [ruby-shoryuken/shoryuken#732]
Lets say there are 5 processing groups and a concurrency value of 10, which means each group gets a concurrency of 10 and a total of 50 threads will be created. If there are groups that only occasionally receive messages then all of the configured concurrency sit idle and if there are other busy groups that needs extra threads it would limit its processing capabilities. How about if there is an option to maintain this concurrency pool globally where groups can share the concurrency when they are not in use. 

```
concurrency: 10
groups:
  group1:
    concurrency: 10
    queues:
      - queue1
  group2:
    concurrency: 10
    delay: 10
    queues:
      - queue2
     .
     .
     .
  group5:
    concurrency: 10
    delay: 10
    queues:
      - queue2
  ```

**Comment by phstc** [comment]
If you want to share concurrency globally, you could remove the groups.

```yaml
concurrency: 25
queues:
  - queue1
  - queue2
  - queue3
``` 

The configuration above will provision 25 threads shared with three queues. 

There's also a [load balancing option](https://github.com/ruby-shoryuken/shoryuken/wiki/Shoryuken-options#load-balancing) that can be an option depending on your need.
