### ISSUE TITLE
Recommended approach to add custom code in relation to concurrency

### ISSUE THREAD

**Issue by karmingc** [ruby-shoryuken/shoryuken#826]
Hi,

We currently use Shoryuken to process SQS messages with the following sample configuration:

```yml
groups:
  group_a:
    concurrency: 2
    queues:
      - "some_queue"
  group_b:
    concurrency: 2
    queues:
      - "some_queue_b"
```

As part of our processing/worker logic, we record metrics and they are then sent to Grafana. However, with the current configuration, there are certain occasions when metrics are recorded with the same labels/attributes but with a different timestamp (due to concurrency). 

We also use Puma to run our Rails application server, and we were able to resolve this by appending the worker pid as an attribute through the `on_worker_boot` hook. We are wondering what would be the recommended approach for Shoryuken?
